#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: $0 <i18n key>"
    exit 1
fi

clear

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
STRING=$1
FOUND=false

grep -n --color=always -r  "_.t('$STRING'" \
    --exclude=$DIR/../public/javascripts/translations/*js \
    $DIR/../app/views/jst \
    $DIR/../public/javascripts | sed 's/.*\.\.\///'
if [ ${PIPESTATUS[0]} -eq 0 ]; then
    FOUND=true
fi

grep -n --color=always -r  "DV.t('$STRING'" \
    --exclude=$DIR/../../viewer/public/javascripts/DV/schema/translation* \
    $DIR/../../viewer/public/javascripts | sed 's/.*\.\./../'
if [ ${PIPESTATUS[0]} -eq 0 ]; then
    FOUND=true
fi

if [ $FOUND == false ]; then
    echo 'Translation not found, falling back to looking for raw string'
    grep -n --color=always -r  $STRING \
        --exclude=$DIR/../public/javascripts/translations/*js \
        $DIR/../app/views/jst \
        $DIR/../public/javascripts | sed 's/.*\.\.\///'

    grep -n --color=always -r  $STRING \
        --exclude=$DIR/../../viewer/public/javascripts/DV/schema/translation* \
        $DIR/../../viewer/public/javascripts | sed 's/.*\.\./../'
fi
