# Sensitive API keys and other secret strings.

defaults : &defaults
  secret_key_base:     # Generate this by running: rake secret
  aws_access_key:      
  aws_secret_key:      
  calais_license:      
  pixel_ping:          DocumentCloud               # The secret hashed key for Pixel Ping (keep in sync with secrets/pixel_ping/:env.json)
  guest_username:      guest                       # The username used for logging into basic auth in staging
  guest_password:      DocumentCloud               # The password used for logging into basic auth in staging
  username:            documentcloud               # The database username
  db_password:         documentcloudVirtualMachine # The database password
  smtp_password:       
  smtp_user:           
  smtp_host:           
  smtp_domain:         
  slack_webhook:       
  google_analytics_id: 

# The "omniauth" section is optional and may be ommitted if third party logins are not used
development :
  <<: *defaults
  omniauth:  
    twitter:
      key:    
      secret: 
    facebook:
      key:    
      secret: 
    google:
      key:    
      secret: 


staging :
  <<: *defaults
  db_host:        # the hostname for your database server
  solr_host:      # the hostname for your solr server
  job_end_point:  # the hostname for your cloud-crowd server
  central_server: # the fully qualified (private) url for the cloud-crowd server (e.g. http://ip-44-555-66-777.ec2.internal:8080)
  bucket:         # the s3 bucket to store both documents and the viewer in

test :
  <<: *defaults

production :
  <<: *defaults
  db_host:        # the hostname for your database server
  solr_host:      # the hostname for your solr server
  job_end_point:  # the hostname for your cloud-crowd server
  central_server: # the fully qualified (private) url for the cloud-crowd server (e.g. http://ip-44-555-66-777.ec2.internal:8080)
  bucket:         # the s3 bucket to store both documents and the viewer in
